Repository ouzi-dev/commit-status-updater, pull requests merged in 2022-10, with the labels that each got.

#512 doc: Fix formatting of examples headers in README
  README.md
Labels: lgtm, approved, ok-to-test, size/XS

#513 doc: Improve presentation of parameters in README
  README.md
Labels: lgtm, approved, ok-to-test, size/M

#515 doc: Update prow link in README
  README.md
Labels: lgtm, approved, ok-to-test, size/XS

#521 major: update dependencies and node
  .eslintrc.json
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
  Makefile
  README.md
  __test__/runner.test.ts
  action.yml
  dist/index.js
  package-lock.json
  package.json
  src/githubHelper.ts
  src/inputsHelper.ts
  src/runner.ts
  tsconfig.json
Labels: lgtm, approved, size/XXL

#522 fix: added make function to fix git tag
  Makefile
  package-lock.json
  package.json
Labels: lgtm, approved, size/XS
